{
 "title": "Hosted Grafana Synthetic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Login",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_10.result'))"
    }
   ]
  },
  {
   "title": "Time to Login (cold)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('name=~hosted_grafana.step_\\d\\d.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "Time to Login (cold)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(seriesByTag('name=~hosted_grafana.step_\\d\\d.duration'))"
    }
   ]
  },
  {
   "title": "Time to Login (hot)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(seriesByTag('name=~hosted_grafana.step_10.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "Time to Login (hot)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(seriesByTag('name=~hosted_grafana.step_10.duration'))"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "STEP 1: Connect",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_01.result'))"
    }
   ]
  },
  {
   "title": "STEP 2: Session Cookie",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_02.result'))"
    }
   ]
  },
  {
   "title": "STEP 3: Login Redirect",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_03.result'))"
    }
   ]
  },
  {
   "title": "STEP 4: Get Auth Token",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_04.result'))"
    }
   ]
  },
  {
   "title": "STEP 5: Redirect",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_05.result'))"
    }
   ]
  },
  {
   "title": "STEP 6: POST Auth ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_06.result'))"
    }
   ]
  },
  {
   "title": "STEP 7: Get OAUTH Clients ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_07.result'))"
    }
   ]
  },
  {
   "title": "STEP 8: Get OAUTH Grants ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_08.result'))"
    }
   ]
  },
  {
   "title": "STEP 9: Get OAUTH Token ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_09.result'))"
    }
   ]
  },
  {
   "title": "STEP 10: Login with Token",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_10.result'))"
    }
   ]
  },
  {
   "title": "STEP 11: Validate Login",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(seriesByTag('name=hosted_grafana.step_11.result'))"
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "STEP 1: Connect",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_01.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 2: Session Cookie",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_02.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 3: Login Redirect",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_03.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 4: Get Auth Token",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_04.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 5: Redirect",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_05.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 6: Post Auth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_06.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 7: Get OAUTH Clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_07.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 8: Get OAUTH Grants",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_08.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 9: Get OAUTH Token",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_09.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 10: Login with Token",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_10.duration')), 'duration')"
    }
   ]
  },
  {
   "title": "STEP 11: Validate Login",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(seriesByTag('name=hosted_grafana.step_11.duration')), 'duration')"
    }
   ]
  }
 ]
}